name: QA Merge Notifier

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Gather PR info
        uses: 8BitJonny/gh-get-current-pr@2.0.0
        id: PR
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Verbose setting SHA when using Pull_Request event trigger to fix #16
          sha: ${{ github.event.pull_request.head.sha }}
      - name: Check if it is release PR
        if: success()
        run: |
          if [[ "${{ steps.PR.outputs.pr_title }}" == "chore(release)"* ]]; then
            echo Release PR detected
            echo ${{ toJSON(fromJSON(steps.PR.outputs.pr)) }}
          else
            echo Action will now exit
            exit 1
          fi
      - name: Post QA merge notification
        if: success()
        env:
          teamsWebhook: ${{ secrets.LHT_DEV_TEAMS_WEBHOOK }}
          prJSON: ${{ toJSON(fromJSON(steps.PR.outputs.pr)) }}
          prBase: ${{ fromJSON(steps.PR.outputs.pr).base.ref }}
          prNumber: ${{ steps.PR.outputs.number }}
          prTitle: ${{ steps.PR.outputs.pr_title }}
          prBody: ${{ steps.PR.outputs.pr_body }}
          prCreatedAt: ${{ steps.PR.outputs.pr_created_at }}
          prUrl: ${{ steps.PR.outputs.pr_url }}
        run: |
          curl --location --request POST '${{ env.teamsWebhook }}' \
            --header 'content-type: application/x-www-form-urlencoded' \
            --header 'x-github-event: pull_request' \
            --data-urlencode 'payload={
              "action": "closed",
              "pull_request": {
                "number": ${{ env.prNumber }},
                "html_url": "${{ env.prUrl }}",
                "title": "${{ env.prBase }} Merge: ${{ env.prTitle }}",
                "body": "Please allow ~15min for build to deploy.\n ${{ env.prBody }}",
                "updated_at": "${{ env.prCreatedAt }}"
              },
              "repository": {
                "name": "test",
                "full_name": "JANA-Technology-Test/test"
              },
              "sender": {
                "login": "Merge Notification",
                "avatar_url": "https://avatars.githubusercontent.com/u/34035211?v=4"
              }
            }'
